apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-data
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: adguard
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adguard
    spec:
      automountServiceAccountToken: false
      containers:
        - name: adguard
          image: adguard/adguardhome:v0.107.73@sha256:7fbf01d73ecb7a32d2d9e6cef8bf88e64bd787889ca80a1e8bce30cd4c084442
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 3000
              name: setup
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /
              port: http
            periodSeconds: 30
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /
              port: http
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 192Mi
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
          volumeMounts:
            - mountPath: /opt/adguardhome/conf
              name: data
              subPath: conf
            - mountPath: /opt/adguardhome/work
              name: data
              subPath: work
      terminationGracePeriodSeconds: 30
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: adguard-data
---
apiVersion: v1
kind: Service
metadata:
  name: adguard
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: adguard
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-lan
spec:
  externalTrafficPolicy: Local
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: dns-tcp
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: dns-udp
    - name: setup
      port: 3000
      protocol: TCP
      targetPort: setup
  selector:
    app.kubernetes.io/name: adguard
  type: LoadBalancer
