apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - storage.yaml
  - torrent.yaml
  - arr.yaml
  - ingress.yaml
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: homelab-media
