apiVersion: v1
data:
    OPENCLAW_GATEWAY_PASSWORD: ENC[AES256_GCM,data:y2jPeFxL6aqz6vn3,iv:JT4UApjYXd20YKI9ZN6jr50imjlnF5qyDWMFi+yBXn0=,tag:3J1zH2Bdv0B6IjhHSIQfig==,type:str]
    OPENCLAW_GATEWAY_TOKEN: ENC[AES256_GCM,data:XfpBSGTK5VCEizwq+kosL+ehelYcRTb5k3FJrQSwfVyCMLh4rjDnbtoBLYN26wgtsTEhjfoaIfn0v2/Tq4lxAKDm2CZvLVQTVsLSdGvapYn4juQRbFyUDw==,iv:suYbmKOA11IGm+r+zKEK7873Hi2YKGt1YaZ/rZ5+e7A=,tag:YMvrILFIaVRUpE1JGHfqcg==,type:str]
kind: Secret
metadata:
    name: openclaw-env
    namespace: homelab
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtTXFxaElMT010Z0JYb3NM
            a2xpTzUvR205dXROSzJiWFdvenNURTZTb0NJCjdaRUNuRDhnMjlrbnEvZTdvd0Nn
            V1VOeFpzeklqcUUrQ2VMVHk3eGJmQzQKLS0tIFREc2NTUmZwV0Q3dWpLVTh1K1JC
            Qis3Q0NXMkdhakw0Z0xRK1dkRVlCeHMKuHI5qw/oFZUk8TbM2f7fYUCCZvf6uAwz
            DatZoiwLWkdEcl1f5A2JvjQqx8U85QHKm5oZSCctzulIqgy1zQ4NgQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12hk7pltj3tvnc5gz2durrz754rxwpjje25zd6crgdqncdmc549wqyvewz0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T01:09:02Z"
    mac: ENC[AES256_GCM,data:zqYbps9oKh4ehGIgftRzXhv/6z/MeuUZd+CGJBlzw2ysRgWYfQFjJd0kjZeiH9vC0q7+E0XL5s/U03wAFAS6c3C4hwdlvnFuAqN3oztSkF+x5asbYA37bpHr6j1lWQwbGrPQ613gBH0LRoqK5gBS8oBgC+kQ0jrb8Arh2hI1bJs=,iv:GUEG/wWT+ZK5tABlJdRdhFmwT++I1xftvzsRImefZbc=,tag:tWMPPT3arGmXoUmUI4vBUw==,type:str]
    version: 3.13.2
