apiVersion: v1
data:
    settings.yml: ENC[AES256_GCM,data:CVY/ZicRUkEID8b4hhINfznquvoV1DKhXaamXK5GE+1u5Cj8JEi8GUeUq1QuJNCMAEguvJ70qGrxpOLGY+ldoetvqp/snZ6EWDHEjkrWJ86CjfqvQz7wnGYfZc5hkN4UBJN/EmqrTCAAQBsAlrPuV5zAV7lTtsDbSVyLVp+7vdUW0/yiK7ruyrXAlLepnDy5KdNNUtCdvxPUR3gAaDEzLW/ueUSyRVW9dKcFl5UM4I92nu3Mr6lTTFb5TBXmhFgWIqLeHvtI4ChWDOXbjrgjrfZBPFJl1f+y6HwkIKuNWckTyL2KIIWBr1te6GOzxp19BX42hziJiOynCNiV/9K8gJRUdwBoplBKrsYare6bUHJG4NiVI4yWrDR/AprUA+PJj5SUPksjXBMshsDRyaiDsTpYx66j9NeqmI2KbXXfed5vw8ZuYmIBxag/BMGhP3Ysvrg3ZC4GMJfnEyUatqKu3Rn/LfajFwrqRiRrhPCHkb1ovWiGLLqJw6tTlAeipL01hdzg0bte1V9cjfMb9xFIiZ94No6PXzi5Plbxuojc2jcs6KpduFBMUJ1i1HCQZdqn99/xQ2nnqGT0ALNTaqleZP5bfWOj9xsjWQlfZxDKJSX3JDwn,iv:3U1D6EziOYjbdAi0RPC/15jz2sceACkdLOLQG/Mh5qg=,tag:Cb8zTT8My2359passgjqBg==,type:str]
kind: Secret
metadata:
    name: searxng-settings
    namespace: homelab
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmd1l0MXFoaW8zcUJ6QjFr
            K2lwRnlkejJGRnRnalNLWStuT0pDU3VtZVg0CmV6OW5UVDlteW1tQ3BwVysxL2Zo
            Mjk5MGZCZ0xlMjlOT0Z3aVg4WE4yMDAKLS0tIGJLYXhpOW1EbUh3bDlDbm51Q0lp
            Ri9IMzdGYS9TWTJTODJ5YU1HSU1ORmcKT28ZUBSj4dmhYdOhZ91RPc1gcKVyJC/q
            yE8O/L/+ptw6jzPcrpmkg8yPG6PnOCgDJpYUY0RAGhx9hccdHvtEiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age12hk7pltj3tvnc5gz2durrz754rxwpjje25zd6crgdqncdmc549wqyvewz0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-24T01:09:02Z"
    mac: ENC[AES256_GCM,data:ZMf4zSs5sM6h3q4o7nYHHEnLO6qxm7Q5YD6LhxQdei6iHX0lNZTTQ7wqG3nl6oHFtoBi5TMUggEwhOS4JB7Lg+rQ8oEoQvg+tfEmHaiBsZHWIHzZu0jBX4DXeNwVIPpghyH0EUZe+n9GcxdD0YHuuqz1J4lXrbT1OIhbkVR6qX4=,iv:phfDglSTbx4blgbhj+HEXxL0AYGuIclkD3t755Q5WLg=,tag:KnfiAoNLyr60x+I6VHNrPg==,type:str]
    version: 3.13.2
